### ISSUE TITLE
Remote Ip can not input dot.

### ISSUE THREAD

**Issue by RaytacStanley** [thumbb13555/UDP_TCP_ConnectDemo#1]
I found the Remote Ip text box can not input '.'. Fix the error by specifying both android:inputType="numberDecimal" and android:digits="0123456789,." it will display a keyboard with mostly just numbers and punctuation (depending on the user's chosen keyboard). It will also limit the characters accepted as input to those in your digits attributes.

**Comment by thumbb13555** [comment]
Oops, thanks for telling me about the problem and helping me to fix it.
I have marge your fix into my code.
